name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
    paths-ignore:
      - "**.md"
      - "**.ps1"
      - ".editorconfig"
      - "TestFiles/*"
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '**/*.yml'
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]  # Only run when PR is created or updated

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    if: github.event_name != 'push' || github.event.pull_request == null  # Prevents duplicate runs

    steps:
      # uses GitHub's checkout action to checkout code form the release branch
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # sets up Java
      - name: Set up Java
        uses: actions/setup-java@v4.7.0
        with:
          distribution: "microsoft"
          java-version: "11"

      # sets up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.0
        with:
          global-json-file: ./global.json

      # sets up MAUI
      - name: Set up MAUI
        run: dotnet workload install maui-android --source https://api.nuget.org/v3/index.json

      - name: Install WASM workload
        run: dotnet workload install wasm-tools
  
      - name: Restore dependencies
        run: dotnet restore -p:SelfContained=true

      - name: Build Web
        run: dotnet build Pkmds.Web/Pkmds.Web.csproj --configuration Release --no-restore

      - name: Build Android
        run: dotnet build Pkmds.Maui/Pkmds.Maui.csproj --configuration Release -f net9.0-android --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build
